server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Alex/Repo/KG_Test/fyp-sample-app/config-repo
          clone-on-start: true
  application:
    name: config-server
